django_instagram/django_instagram/urls.py
# -*- coding:UTF-8 -*-
"""django_instagram URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import *
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^accounts/',include('django.contrib.auth.urls',namespace='auth')),
    url(r'^$',Main.as_view(),name='main'),
    url(r'',include('social_django.urls',namespace='social'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

django_instagram/post/urls.py
from django.conf.urls import url
from post.views import *
app_name = 'post'
urlpatterns = [
    url(r'^$',post_list,name='post_list'),
    url(r'^profile/edit/$',profile_update,name='profile_update'),
    url(r'^new/$', Post_create.as_view(), name='post_create'),
    url(r'^modification/(?P<pk>\d+)/$', post_update, name='post_update'),
    url(r'^delete/(?P<pk>\d+)/$', post_delete, name='post_delete'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),
    url(r'^(?P<author>\w+)/$',user_post,name='user_post_list'),
    url(r'^(?P<author>\w+)/follow/$', post_follow, name='follow'),
    url(r'^(?P<pk>\d+)/like/$',post_like,name='like'),
    url(r'^search', post_search, name='search'),
    url(r'^tag/(?P<tag>\w+)/$',tag_list,name='tag_list'),
    url(r'^reple/(?P<pk>\d+)/$', post_reple, name="post_reple"),
    url(r'^reples/(?P<pk>\d+)/$', more_reples, name="more_reples"),
    url(r'^ajax/list/(?P<author>\w+)/$',more_post_list,name="more_post_list")
]

django_instagram/templates/base_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>instagram</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/common.css'%}">
    <link rel="stylesheet" href="{% static 'css/base_home.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
</head>
<body>

    <div id="wrap">
        <header>
            <div>
                <h1><a href="{% url 'post:post_list' %}"></a></h1>
                <ul id="search">
                    <li>
                        <input type="text" placeholder="검색" id="search-form">
                        <ul id="search-list">
                        </ul>
                    </li>
                </ul>
                <ul id="nav-list">
                    <li><a href="{% url 'post:post_create' %}"></a></li>
                    <li><a href=""></a></li>
                    <li><a href="{% url 'post:user_post_list' user.username %}"></a></li>
                </ul>
            </div>
        </header>
        <section>
            <article>
                {% block content %}
                {% endblock %}
            </article>
        </section>
        <footer>

        </footer>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script>
    $("#search-form").change(function(){
            $("#search-list").html("");
            var word = $(this).val();
            if(word==""){
                return;
            }else{
                var url;
                var user_post;
                $.ajax({
                    url:'{% url "post:search" %}',
                    data:{
                        'word':word
                    },
                    dataType:'json',
                    success:function(data){
                        console.log(data)
                        if(data.flag){
                            if(data.data) {
                                for (var i = 0; i < data.data.length; i++) {
                                    user_post = data.data[i].username;
                                    url = "{% url 'post:user_post_list' 1234 %}".replace(/1234/, user_post.toString());
                                    $("#search-list").append(
                                        "<li><div><img src='/media/" + data.profile[i]['avatar'] + "'></div><div class='profile-name'><a href=" + url + " class='user-post-list-link'>" + data.data[i]['username'] + "</a></div></li>"
                                    );
                                }
                            }
                            if(data.tag){
                                url = "{% url 'post:tag_list' 1234%}".replace(/1234/,data.tag);
                                $("#search-list").append(
                                        "<li><div class='profile-name'><a href=" + url + " class='user-post-list-link'>#" + data.tag + "</a></div></li>"
                                    );
                            }
                        }
                    }
                });
            }
        });
    {% block javascript %}
    {% endblock %}</script>
</body>
</html>

django_instagram/templates/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>instagram</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
</head>
<body>
{% if user.is_anonymous %}
<div id="wrap">
    <header>
        <h1><a href="{% url 'main' %}">Instagram</a></h1>
    </header>
    <section>
        <article>
            <div class="iphone">
                <img src="{% static 'img/iphone.png' %}" alt="iphone">
            </div>
    {% block content %}
    {% endblock %}
        </article>
    </section>
    <footer>
        <p>made by Leeyejin</p>
    </footer>
</div>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script>
    {% block javascript %}
    {% endblock %}</script>

</body>
</html>
{% else %}
    <script>
        location.href={% url 'post:post_list' %};
    </script>
{% endif %}